### ISSUE TITLE
Auto Theme Switching Due To System Failed

### ISSUE THREAD

**Issue by oceanondawave** [Clarkkkk/vscode-auto-light-dark-theme#1]
Hello @Clarkkkk, I would like to know about the auto theme switching due to the system preference feature. Although I configured correctly what needed to be turned on and selected as below, the feature did not work as expected. Only the manual switching feature worked. Here is what I have configured:
1. **Auto Toggle** is checked
2. **Light Theme** and **Dark Theme** are selected
3. **Toggle Setting** is `system`
Here is the video capturing my error:

https://github.com/Clarkkkk/vscode-auto-light-dark-theme/assets/62211294/ed60fcf7-f56a-476f-9810-ce874538df54

Thank you!

**Comment by Clarkkkk** [comment]
It works fine on my macbook. 

Are you using a third party app to toggle the dark mode? Can you toggle to dark mode via the control center?

BTW, what is your vscode version and macOS version? Can you update your vscode to the latest version and try again? If that's not helping, can you open the settings JSON by `command+shift+p` and copy the whole settings here? (of cource you may need to remove the sensitive or private info)

**Comment by oceanondawave** [comment]
> It works fine on my macbook.
> 
> Are you using a third party app to toggle the dark mode? Can you toggle to dark mode via the control center?
> 
> BTW, what is your vscode version and macOS version? Can you update your vscode to the latest version and try again? If that's not helping, can you open the settings JSON by `command+shift+p` and copy the whole settings here? (of cource you may need to remove the sensitive or private info)

Hi, thanks for replying to me. Yeah, even though I toggle Dark Mode/Light Mode via System Settings, the issue persists. I've also tried other extensions but they did not work as well. Maybe Visual Studio Code already has the built-in functionality to switch the themes automatically based on the system and it may conflict with my settings, so it's not because of your extension. Anyway, thanks for your support. I have decided to use the feature that automatically switches the themes based on a certain time.

**Comment by Clarkkkk** [comment]
You are right, vscode has built-in support for theme switching based on the system preference. This extension is simply using the built-in ability internally when setting `Toggle Setting` to `system`. In fact, if all you need is to toggle themes based on the system preference and nothing else, you do not need any extensions to do it.

You can disable all the theme toggling relevant extensions and restart vscode. Search `autoDetectColorScheme` and set them up to see if it works.

![image](https://github.com/Clarkkkk/vscode-auto-light-dark-theme/assets/66827108/b693d31c-fd87-4212-bf58-7708473cae58)

**Comment by oceanondawave** [comment]
> You are right, vscode has built-in support for theme switching based on the system preference. This extension is simply using the built-in ability internally when setting `Toggle Setting` to `system`. In fact, if all you need is to toggle themes based on the system preference and nothing else, you do not need any extensions to do it.
> 
> You can disable all the theme toggling relevant extensions and restart vscode. Search `autoDetectColorScheme` and set them up to see if it works.
> 
> ![image](https://private-user-images.githubusercontent.com/66827108/307593115-b693d31c-fd87-4212-bf58-7708473cae58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NzI1OTcsIm5iZiI6MTcwODg3MjI5NywicGF0aCI6Ii82NjgyNzEwOC8zMDc1OTMxMTUtYjY5M2QzMWMtZmQ4Ny00MjEyLWJmNTgtNzcwODQ3M2NhZTU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDE0NDQ1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0MDdmZmIxZTgwMjEwYjczZTk2NWMzYTg4YmQ5YjQ0NTAwYTVjNmQ1ODdhMTY2Mjg2OWIxYzU1ZGIwYjQ3YTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x-M2DZ90fs84W1XWnyZPqT8CzbnHuD4OMf0uTUKsNy4)

Thank you! I appreciate your support.
